import { CauseDefinition } from '../types/catalog';
import { CauseId } from '../types/domain';

export const CAUSES: readonly CauseDefinition[] = [
  {
    id: 'energia',
    icon: '🔌',
    label: 'Falta de Energia Comercial',
    category: 'Energia Elétrica',
    textFullOutage: 'Interrupção no fornecimento de energia elétrica da concessionária no POP/região.',
    textSlowDegraded: 'Oscilações de energia elétrica na região gerando intermitência nos equipamentos.',
    immediateAction: 'Sistemas de contingência (baterias/gerador) ativados. Monitorando retorno com a concessionária.',
    technicalCause: 'Interrupção de energia da concessionária',
    finalReportSummary: 'Interrupção de energia da concessionária que superou a autonomia do banco de baterias.',
  },
  {
    id: 'fibra',
    icon: '✂️',
    label: 'Rompimento de Cabo Óptico',
    category: 'Infraestrutura Óptica',
    textFullOutage: 'Rompimento físico de cabo óptico em trecho troncal/distribuição.',
    textSlowDegraded: 'Instabilidade e desvio de rota por dano parcial em cabo óptico.',
    immediateAction: 'Equipes de fusão óptica em deslocamento prioritário para o local do rompimento.',
    technicalCause: 'Rompimento de cabo óptico (Backbone/Acesso)',
    finalReportSummary: 'Rompimento físico de cabo óptico sanado mediante fusão e substituição de vão em campo.',
  },
  {
    id: 'obra',
    icon: '🚧',
    label: 'Dano por Obra de Terceiros',
    category: 'Interferência Externa',
    textFullOutage: 'Interrupção causada por maquinário de obras de terceiros atingindo cabo óptico.',
    textSlowDegraded: 'Avaria parcial em infraestrutura óptica causada por intervenção de terceiros na via pública.',
    immediateAction: 'Equipe técnica no local isolando o dano e iniciando reconstituição da rota.',
    technicalCause: 'Dano físico em infraestrutura por obra de terceiros',
    finalReportSummary: 'Intervenção de terceiros na via pública provocou rompimento do circuito óptico.',
  },
  {
    id: 'equip',
    icon: '🖥️',
    label: 'Falha em Hardware de Rede',
    category: 'Hardware / Equipamento',
    textFullOutage: 'Falha crítica de hardware em equipamento concentrador/distribuição de rede.',
    textSlowDegraded: 'Instabilidade de tráfego decorrente de falha intermitente em equipamento ativo.',
    immediateAction: 'Componente isolado pelo NOC. Procedimentos de substituição por sobressalente iniciados.',
    technicalCause: 'Falha de hardware (Switch/Roteador/OLT)',
    finalReportSummary: 'Substituição física de hardware danificado e validação de tráfego concluída.',
  },
  {
    id: 'operadora',
    icon: '🏢',
    label: 'Falha em Link de Trânsito IP',
    category: 'Trânsito IP / Operadora',
    textFullOutage: 'Indisponibilidade de acesso decorrente de falha no circuito de trânsito IP da operadora parceira.',
    textSlowDegraded: 'Degradação e aumento de latência provocados por instabilidade no enlace da operadora parceira.',
    immediateAction: 'Chamado crítico sob escalonamento de prioridade máxima junto à operadora fornecedora.',
    technicalCause: 'Falha em circuito upstream / Operadora parceira',
    finalReportSummary: 'Normalização executada pela operadora parceira após atuação em infraestrutura externa.',
  },
  {
    id: 'ataque',
    icon: '🛡️',
    label: 'Ataque Cibernético (DDoS)',
    category: 'Segurança Cibernética',
    textFullOutage: 'Sobrecarga de tráfego por ataque volumétrico direcionado à infraestrutura de rede.',
    textSlowDegraded: 'Lentidão e perda pontual de pacotes devido à mitigação de ataque DDoS em andamento.',
    immediateAction: 'Políticas de mitigação, descarte de tráfego malicioso e regras de scrubbing ativadas.',
    technicalCause: 'Ataque volumétrico distribuído (DDoS)',
    finalReportSummary: 'Ataque neutralizado pelas ferramentas de scrubbing e filtros de mitigação de borda.',
  },
  {
    id: 'manut',
    icon: '🔧',
    label: 'Manutenção Programada',
    category: 'Manutenção Planejada',
    textFullOutage: 'Interrupção temporária para execução de janela técnica programada de melhorias.',
    textSlowDegraded: 'Oscilações temporárias em virtude de intervenção técnica homologada na rede.',
    immediateAction: 'Procedimentos técnicos em andamento estritamente dentro da janela programada.',
    technicalCause: 'Janela de manutenção preventiva/melhoria',
    finalReportSummary: 'Intervenção programada concluída e validada conforme planejamento técnico.',
  },
  {
    id: 'sistema',
    icon: '📱',
    label: 'Indisponibilidade de Sistemas',
    category: 'Sistemas Internos',
    textFullOutage: 'Indisponibilidade nas centrais de atendimento e sistemas internos. Conexão de internet íntegra.',
    textSlowDegraded: 'Lentidão no processamento dos sistemas de atendimento. Conexão de clientes normal.',
    immediateAction: 'Equipes de TI atuando na estabilização dos servidores e banco de dados.',
    technicalCause: 'Falha em servidor/sistema interno',
    finalReportSummary: 'Sistemas restabelecidos após intervenção na camada de aplicação interna.',
  },
  {
    id: 'nsei',
    icon: '❓',
    label: 'Causa em Diagnóstico Técnico',
    category: 'Diagnóstico em Andamento',
    textFullOutage: 'Indisponibilidade de conexão na localidade. Ponto de falha sob diagnóstico técnico pelo NOC.',
    textSlowDegraded: 'Instabilidade de conexão sob monitoramento ativo pelo NOC para isolamento de causa raiz.',
    immediateAction: 'NOC e engenharia de rede em telemetria ativa para identificação e contenção do evento.',
    technicalCause: 'Em diagnóstico e triagem técnica pelo NOC',
    finalReportSummary: 'Causa raiz identificada durante atendimento técnico e corrigida em campo.',
  },
] as const;

export const CAUSES_MAP: Record<CauseId, CauseDefinition> = CAUSES.reduce((acc, c) => {
  acc[c.id] = c;
  return acc;
}, {} as Record<CauseId, CauseDefinition>);
